### ISSUE TITLE
TypeError: Cannot set property 'end_time' of undefined

### ISSUE THREAD

**Issue by kleysonr** [emilsedgh/modem#14]
I'm trying to run the following code on Windows 7:

```
/* Usage: node send_sms.js /path/to/device xxxxyyzz "Foo Bar" */

function err(message) {
  console.log('Usage: node send_sms.js /path/to/device xxxxyyzz "Foo Bar"');
  process.exit();
}

var device   = 'COM11';
var receiver = '5562XX1685XX';
var text     = 'ola mundo';

console.log('iniciando');

var modem = require('modem').Modem();
modem.open(device, function() {
  modem.sms({
    receiver:receiver,
    text:text,
    encoding:'7bit'
  }, function(err, sent_ids) {
    console.log('>>', arguments);
    if(err)
      console.log('Error sending sms:', err);
    else
      console.log('Message sent successfully, here are reference ids:', sent_ids.join(','));
  });
});
```

But I'm getting the error:

```
D:\serialport>node app4.js
>> { '0': null, '1': [ '' ] }
Message sent successfully, here are reference ids:

D:\serialport\node_modules\modem\lib\modem.js:176
                this.queue[0]['end_time'] = new Date();
                                          ^
TypeError: Cannot set property 'end_time' of undefined
    at EventEmitter.<anonymous> (D:\serialport\node_modules\modem\lib\modem.js:176:43)
    at Array.forEach (native)
    at EventEmitter.modem.dataReceived (D:\serialport\node_modules\modem\lib\modem.js:123:15)
    at SerialPort.emit (events.js:95:17)
    at Object.module.exports.raw [as parser] (D:\serialport\node_modules\serialport\parsers.js:8:13)
    at SerialPort.options.dataCallback (D:\serialport\node_modules\serialport\serialport.js:143:15)
```

Trying to debug the module, I've realized that the line 176 is performed 3 times but the error happens just on the 3rd time.

Kleyson Rios.

**Comment by hieucdtspk** [comment]
Dear @kleysonr,

The root cause of this problem regarding to AT configuration for SMS, TEXT mode or PDU mode (note that this lib working well with PDU mode only!).
So you need to factory reset your modem and make sure switch modem in correct PDU mode before running app. you can manually open the terminal and anter some AT command as following:
AT&F          // to factory reset modem
AT&W         // to save the current configuration of modem to non-volatile memory
AT+CMGF=0     // to switch to PDU mode
AT+CSCS="GSM"   // 7bit mode
Now, your app should work with modem properly!

Regards,
HieuNT

**Comment by emonik** [comment]
@hieucdtspk This lib works just fine with TEXT MODE , in my case the issue was due to the device storage being 50% full ( New smses wasn't passing through & I don't know why , p.s : I was debugging with "**minicom**" ) .
Keeping the storage capacity below 50% for my case was the solution.

P.S: I had the same issue when I was running USSD codes with another library & listening for smses with this one ( I Ignored the +CUSD event & everything was fine )

@kleysonr : Does this fall within your case ?
