### ISSUE TITLE
Open not exist serialport throw error

### ISSUE THREAD

**Issue by terrywong2** [emilsedgh/modem#27]
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Serialport not open.
    at SerialPortFactory.SerialPort.close (/Users/terry/Desktop/iRXBot/modem/node_modules/modem/node_modules/serialport/serialport.js:476:17)
    at EventEmitter.modem.close (/Users/terry/Desktop/iRXBot/modem/node_modules/modem/lib/modem.js:110:19)
    at SerialPort.<anonymous> (/Users/terry/Desktop/iRXBot/modem/node_modules/modem/lib/modem.js:104:19)
    at SerialPort.emit (events.js:107:17)
    at SerialPort.callback (/Users/terry/Desktop/iRXBot/modem/node_modules/modem/node_modules/serialport/serialport.js:101:16)
    at /Users/terry/Desktop/iRXBot/modem/node_modules/modem/node_modules/serialport/serialport.js:224:11
```

**Comment by ianiD** [comment]
Bump
